const content={
 pump:{score:"82",scoreNote:"+6 points since prior review",coverage:"91",coverageNote:"248 linked evidence records",gaps:"7",gapsNote:"2 need action this week",risk:"38",riskNote:"4 awaiting final evidence"},
 catheter:{score:"76",scoreNote:"+4 points since prior review",coverage:"86",coverageNote:"196 linked evidence records",gaps:"10",gapsNote:"3 need action this week",risk:"31",riskNote:"6 awaiting final evidence"}
};
const project=document.getElementById("project");
function setProject(key){const d=content[key];document.getElementById("score").innerHTML=d.score+"<small>/100</small>";document.getElementById("scoreNote").textContent=d.scoreNote;document.getElementById("coverage").innerHTML=d.coverage+"<small>%</small>";document.getElementById("coverageNote").textContent=d.coverageNote;document.getElementById("gapsTotal").textContent=d.gaps;document.getElementById("gapsNote").textContent=d.gapsNote;document.getElementById("riskControls").innerHTML=d.risk+"<small>/42</small>";document.getElementById("riskNote").textContent=d.riskNote}
project.addEventListener("change",e=>setProject(e.target.value));
const phases={Concept:"Review user needs, intended use, and the early risks that shape the development plan.","Design input":"Translate user needs into measurable, reviewable engineering requirements.","Design output":"Connect drawings, specifications, and design outputs to their intended requirements.","V&V":"Focus on objective evidence that verifies requirements and validates intended use.","Design transfer":"Confirm manufacturing readiness, process controls, and complete transfer evidence.","Regulatory":"Organize submission evidence, risk information, and review-ready documentation."};
document.querySelectorAll("#lifecycleTabs button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("#lifecycleTabs button").forEach(b=>b.classList.remove("active"));button.classList.add("active");document.getElementById("lifecycleCopy").textContent=phases[button.textContent]}));
const about=document.getElementById("aboutDialog");document.getElementById("aboutButton").onclick=()=>about.showModal();document.getElementById("closeDialog").onclick=()=>about.close();
document.getElementById("showAll").onclick=()=>{document.getElementById("gaps").insertAdjacentHTML("beforeend",'<div class="gap"><span class="priority medium">Medium</span><div><b>RQ-012 · Battery endurance requirement</b><p>Traceability review is scheduled for the next design-control checkpoint.</p></div><span class="owner">Owner: Systems</span></div>');document.getElementById("showAll").disabled=true;document.getElementById("showAll").textContent="All shown"};